refactor(CI): CI 파이프라인 수정

diff --git a/.github/workflows/spring-boot-gradle-ci.yml b/.github/workflows/spring-boot-gradle-ci.yml
--- a/.github/workflows/spring-boot-gradle-ci.yml
+++ b/.github/workflows/spring-boot-gradle-ci.yml
@@ -1,23 +1,37 @@
-name: Spring Boot Gradle CI 
+name: Spring Boot Gradle CI
 
-on: [pull_request]
+on:
+  pull_request:
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - name: Set up JDK 21
-      uses: actions/setup-java@v4.2.1
-      with:
-        java-version: '21'
-        distribution: 'adopt'
-        cache: 'gradle'
+      - name: Set up JDK 21
+        uses: actions/setup-java@v4.2.1
+        with:
+          java-version: '21'
+          distribution: 'adopt'
+          cache: 'gradle'
 
-    - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
 
-    - name: Build with Gradle
-      run: ./gradlew build
+      - name: Create application-test.yml from secret
+        run: echo "${{ secrets.TEST_YML }}" > application-test.yml
+
+      - name: Build and test with Gradle
+        run: ./gradlew build test --args='-Dspring.profiles.active=test'
+
+      - name: Check build status
+        run: |
+          if [[ $? -ne 0 ]]; then
+            echo "Build failed!"
+            exit 1
+          else
+            echo "Build succeeded!"
+          fi
